name       : cups
version    : 2.2.6
release    : 17
source     :
    - https://github.com/apple/cups/releases/download/v2.2.6/cups-2.2.6-source.tar.gz : 40385778c2b3bdf55030d1c999734e22774c79e3425d91339ce677825620169b
homepage   : https://www.cups.org/
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.core
summary    : The Common Unix Printing System
description: |
    The Common Unix Printing System (CUPS) is a print spooler and associated utilities. It is based on the "Internet Printing Protocol" and provides printing services to most PostScript and raster printers.
emul32     : yes
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig32(dbus-1)
    - pkgconfig32(gnutls)
    - pkgconfig32(liblzma)
    - pkgconfig32(libudev)
    - pkgconfig32(libusb-1.0)
    - acl-32bit-devel
    - attr-32bit-devel
    - libgcrypt-32bit
    - libpaper-32bit-devel
    - pam-32bit-devel
rundeps    :
    - devel : libgnutls-devel
    - 32bit-devel : libgnutls-32bit-devel
patterns   :
    - devel :
        - /usr/bin/cups-config
        - /usr/share/man/man1/cups-config.*
setup      : |
    %patch -p0 < $pkgfiles/cups-fix-install-perms.patch
    %patch -p1 < $pkgfiles/cups-systemd-socket.patch

    # Remove ".SILENT" rule for verbose output (bug #524338)
    sed -i 's#^.SILENT:##g' Makedefs.in

    ex_opts=""
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ex_opts="-disable-avahi --disable-dnssd --disable-systemd"
    fi

    %configure $ex_opts --prefix=/usr \
               --enable-libpaper \
               --enable-relro \
               --enable-webif \
               --with-cups-user=lp \
               --with-cups-group=lp \
               --with-system-groups=lpadmin \
               --with-rundir=/run/cups \
               --without-rcdir
build      : |
    %make
install    : |
    %make_install BUILDROOT=$installdir

    if [[ -z "${EMUL32BUILD}" ]]; then
        install -D -m00644 $pkgfiles/cups.sysusers $installdir/%libdir%/sysusers.d/cups.conf
        install -D -m00644 $pkgfiles/cups.tmpfiles $installdir/%libdir%/tmpfiles.d/cups.conf

        # should be pre-enabled
        install -D -d -m00755 $installdir/usr/lib/systemd/system/printer.target.wants
        install -D -d -m00755 $installdir/usr/lib/systemd/system/sockets.target.wants
        install -D -d -m00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
        ln -s ../org.cups.cupsd.service $installdir/usr/lib/systemd/system/printer.target.wants/.
        ln -s ../org.cups.cupsd.socket $installdir/usr/lib/systemd/system/sockets.target.wants/.
        ln -s ../org.cups.cupsd.path $installdir/usr/lib/systemd/system/multi-user.target.wants/.
    fi

    rm -rf $installdir/{run,var}
check      : |
    #make check
